[package]
name = "unreal_server"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
log = "0.4.0"
env_logger = "0.9.0"
lazy_static = "1.4.0"
regex = "1.5.4"
crossbeam = "0.8"
crossbeam-queue = "0.3"