[package]
name = "unreal_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mio = "0.8"
log = "0.4.0"
env_logger = "0.9.0"
lazy_static = "1.4.0"
regex = "1.5.4"
